### ISSUE TITLE
Problem!

### ISSUE THREAD

**Issue by kostya-ten** [olegwtf/p5-IO-Socket-Socks#4]
Use of uninitialized value $IO::Socket::Socks::ISA[1] in constant array element at /home/kostya/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/IO/Socket/Socks.pm line 1913

perl 5.20.1
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"

**Comment by olegwtf** [comment]
Is there any reason you are running your script with `perl -w`?

**Comment by kostya-ten** [comment]
А что плохого?

**Comment by olegwtf** [comment]
http://perldoc.perl.org/warnings.html#What's-wrong-with-*-w*-and-%24%5eW

**Comment by olegwtf** [comment]
Anyway, you are welcome to fix it and make pull request
